# Generated by Django 3.2.13 on 2022-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('1', '🤩'), ('2', '🤩🤩'), ('3', '🤩🤩🤩'), ('4', '🤩🤩🤩🤩'), ('5', '🤩🤩🤩🤩🤩')], max_length=1),
        ),
    ]
